services:
  db:
   image: postgres
   container_name: psql_db
   restart: always
   environment:
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=localhost
      - POSTGRES_DB = days
   ports:
     - 5432:5432

  fe:
    build: ./FrontEnd/
    ports:
     - 80:80

  be:
    build: ./BackEnd/
        
    ports:
      - 5000:80
    depends_on:
     - db
