services:
  db:
    image: postgres
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks: 
      - todo-network

  be:
    container_name: backend
    build: ./BackEnd/
    depends_on:
      - db
    ports:
      - 8080:8088
    networks: 
      - todo-network

  fe:
    build: ./FrontEnd/
    depends_on:
      - be
    ports:
      - 80:80
    networks: 
      - todo-network



networks: 
  todo-network:
    driver: bridge

volumes:
  pgdata:
