version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks: 
      - todo-network

  be:
    container_name: be
    build: ./BackEnd/
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_SCHEMA: postgres
    depends_on:
      - db
    networks: 
      - todo-network

  fe:
    container_name: fe
    build: ./FrontEnd/
    environment:
      API_URL: "/api/Todo"
    depends_on:
      - be
    networks: 
      - todo-network

  lb:
    image: nginx:alpine
    container_name: lb
    depends_on:
      - be
      - fe
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert.crt:/etc/nginx/ssl/cert.crt:ro
      - ./cert.key:/etc/nginx/ssl/cert.key:ro
    ports:
      - 80:80
      - 443:443
    networks: 
      - todo-network

networks: 
  todo-network:
    driver: bridge

volumes:
  pgdata:
