services:
  db:
    image: postgres:alpine
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks: 
      - todo-network

  be:
    container_name: backend
    build: ./BackEnd/
    depends_on:
      - db
    networks: 
      - todo-network

  fe:
    build: ./FrontEnd/
    depends_on:
      - be
    networks: 
      - todo-network

  lb:
    image: nginx:alpine
    container_name: lb
    depends_on:
    - be
    - fe
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443
    networks: 
      - todo-network

networks: 
  todo-network:
    driver: bridge

volumes:
  pgdata:
